### ISSUE TITLE
Tagging a version for Symfony3

### ISSUE THREAD

**Issue by rodyhaddad** [norzechowicz/aceeditor-bundle#21]
Hi there!

Are you planning on tagging a new version for Symfony3? :)

The fixes already seem in master, but there's no published version for others to pull from.  
Is there anything blocking the new version? If yes, I'd be happy to help out with it.

**Comment by stephen-crowdreactive** [comment]
I agree. The Symfony 3 requirement is BC breaking.

**Comment by norzechowicz** [comment]
I updated master to test it in my pet project https://codevotes.com/ - it works on SF3 more than month already, looks like I can tag stable release, I'll do that soon

**Comment by norzechowicz** [comment]
Hey, thanks for your patience! 
I just released two branches:

* 2.8 - with support for symfony ^2.8
* 3.0 - with support for symfony ^3.0 

master will stay for development purpose
