### ISSUE TITLE
ace.require does not work for all extensions

### ISSUE THREAD

**Issue by payling** [norzechowicz/aceeditor-bundle#35]
As far as I can tell you should be able to require the bundled extensions using ace.require. Unfortunately, doing so for some exts returns undefined. Any help appreciated.

**Not working**
ace.require('ace/ext/beautify')
undefined

ace.require('ace/ext/keybinding');
undefined

**Working examples**
ace.require('ace/ext/language_tools');
object

ace.require('ace/ext/error_marker')
object

**Comment by norberttech** [comment]
hey, could you post the whole error you are getting from browser development console?
