### ISSUE TITLE
Problem integration component in EasyAdmin 2.x

### ISSUE THREAD

**Issue by yoannmorelniji** [norzechowicz/aceeditor-bundle#40]
Hello, 

We use this component in EasyAdmin. 

After the migration Easyadmin version 1 to version 2, we have lost this component and we have no idea for resolve my problem. 

Before Migration
![image](https://user-images.githubusercontent.com/55581970/152505008-93cb8bb3-3891-449a-83aa-e4db4ee8dec7.png)

After Migration
![image](https://user-images.githubusercontent.com/55581970/152505151-b19a956b-206a-4f1c-97dc-bf4f39f28cd8.png)

**Comment by nocive** [comment]
close :see_no_evil:
