### ISSUE TITLE
Bring back dependabot

### ISSUE THREAD

**Issue by norberttech** [norzechowicz/aceeditor-bundle#72]
Some time ago, due to changes in GitHub Action workflows I was trying to migrate this project to renovate from dependabot, that approach failed due to my lack of time and project got stuck in between. 

I tink we can easily bring back dependabot, just like in my other projects.

- [sample config](https://github.com/flow-php/flow/blob/1.x/.github/dependabot.yml)
- [sample auto merge workflow](https://github.com/flow-php/flow/blob/1.x/.github/dependabot.yml)

It automatically merges only patches, but it can also be changed to minors.

**Comment by nocive** [comment]
I have some experience with dependabot, perhaps I can lend a :hand: here.

The stock dependabot configuration should just work (^tm), you'll just have to make some decisions regarding frequency and possibly limit the nr of PRs to have open at the same time at any given point in time.

**Comment by nocive** [comment]
Btw, on a side note, wondering what your thoughts are regarding adding actual static analysis tools like phpstan or psalm (or both).

**Comment by norberttech** [comment]
> I have some experience with dependabot, perhaps I can lend a ✋ here.

Be my guest 😁 Feel free to propose any suitable configuration here, I don't have strong opinion about how dependabot should be set up. 

> Btw, on a side note, wondering what your thoughts are regarding adding actual static analysis tools like phpstan or psalm (or both).

It would not hurt to add psalm or phpstan, however due to strong coupling with Symfony it might be challenging, I simply never had enough time to work on it 😅

**Comment by nocive** [comment]
There are symfony specific plugins for both tools which eliminate most of the false positives and add additional hinting.

In general it's not very tricky to setup, you mostly need to care about having a compiled kernel dumped into `./var/cache` and reference that path in the corresponding plugin configuration.

https://github.com/phpstan/phpstan-symfony
https://github.com/psalm/psalm-plugin-symfony

**Comment by norberttech** [comment]
> There are symfony specific plugins for both tools which eliminate most of the false positives and add additional hinting.
> 
> In general it's not very tricky to setup, you mostly need to care about having a compiled kernel dumped into `./var/cache` and reference that path in the corresponding plugin configuration.
> 
> https://github.com/phpstan/phpstan-symfony https://github.com/psalm/psalm-plugin-symfony

then go for it! 😁

**Comment by nocive** [comment]
https://github.com/norberttech/aceeditor-bundle/pull/76
