### ISSUE TITLE
Migrate project to a different namespace. 

### ISSUE THREAD

**Issue by norberttech** [norzechowicz/aceeditor-bundle#74]
I chose this namespace a long time ago but it feels just a bit too complicated for almost anyone who is not speaking Polish 😅
Would be much better to either move it under NorbertTech namespace or something completely different like AceEditorPhp maybe (I'm open for any other propositions). 

Version 5.0.0 might be a good opportunity for that, since it would also require changing the package name and updating packagist.org

**Comment by norberttech** [comment]
or maybe SymfonyAceBundle or just AceEditorBundle 🤔

**Comment by nocive** [comment]
Although it might feel too long, here's another one :) `NorbertTech\SymfonyAceEditorBundle`

Otherwise `NorbertTech\SymfonyAceBundle` would also fit, i just feel "ace" is too generic :)
